version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile.web
    entrypoint: /entrypoint.sh
    command: python app/server.py
    env_file: backend/.env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - instinct-net
    restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: backend/Dockerfile.scraper
    entrypoint: /entrypoint.sh
    command: python app/tools/scraper_rotation.py
    env_file: backend/.env
    networks:
      - instinct-net
    restart: unless-stopped

  discord:
    build:
      context: .
      dockerfile: backend/Dockerfile.discord
    entrypoint: /entrypoint.sh
    command: python app/tools/discord_bot.py
    env_file: backend/.env
    networks:
      - instinct-net
    restart: unless-stopped

networks:
  instinct-net:
