version: "3.9"
services:
  instinct_app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M  # Increased slightly to handle multiple processes
          cpus: '0.75'
    networks:
      - instinct-net
    # Default command runs a supervisor that manages all three processes
    command: python run_services.py

networks:
  instinct-net: