FROM python:3.11.8-slim

WORKDIR /app

# Install Chromium and other dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium chromium-driver curl unzip gnupg ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV CHROME_BIN=/usr/bin/chromium
ENV CHROMEDRIVER_PATH=/usr/bin/chromedriver

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app

CMD ["python", "app/tools/scraper_rotation.py"]
