FROM python:3.11.8-slim

# Create working directory
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY backend /app

CMD ["python", "app/server.py"]
